version: '3'

services:
  mavros:
    image: ghcr.io/unl-nimbus-lab/arl-swarm/docker/drone:latest
    #image: clustering
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    container_name: mavros
    network_mode: "host"
    volumes:
      - /home/ubuntu/rosbags:/home/rosbags
    devices: 
      - ${PORT}:${PORT}
    command: >
      /bin/bash -c "source /home/catkin_ws/devel/setup.bash &&
                    roslaunch src/clustering_control/launch/clustering_control_container.launch system_ID:=${SYS_ID} clusterID:=${CLUSTER_ID} clusterPosition:=${CLUSTER_POSITION} clusterSize:=${CLUSTER_SIZE} clusterRadius:=${CLUSTER_RADIUS} agentAlt:=${AGENT_ALT} homeLat:=${HOME_LAT} homeLon:=${HOME_LON} homeAlt:=${HOME_ALT} rally1Lat:=${RALLY1LAT} rally1Lon:=${RALLY1LON} rally2Lat:=${RALLY2LAT} rally2Lon:=${RALLY2LON} fcu_url:=${PORT}:${BAUD} tgt_system:=${SYS_ID} tgt_component:=${COMP_ID}"
    restart: unless-stopped